name: waveform
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/hydro-sdk/waveform

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  github: ^8.1.1
  git: ^2.0.0
  http: ^0.13.3
  args: ^2.1.1
  yaml: ^3.0.0
  hydro_sdk_version: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
