name: waveform
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/hydro-sdk/waveform

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  github:
  git:
  http: 
  args: 
  yaml: 
  yaml_modify: 
  hydro_sdk_version: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
