name: waveform
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/hydro-sdk/waveform

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  github: ^7.0.4
  meta: ^1.3.0-nullsafety.3
  hydro_sdk_version: ^1.2.0
  git: ^1.0.1
  http: ^0.12.2
  args: ^1.6.0
  yaml: ^2.2.1
  yaml_modify: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
